# Generated by Django 5.2.7 on 2025-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EFarmerConnectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_CONFIRMATION', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_BK', 'Bank of Kigali'), ('BANK_EQUITY', 'Equity Bank'), ('CREDIT_CARD', 'Credit Card')], max_length=50),
        ),
    ]
