# Generated by Django 5.2.7 on 2025-12-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EFarmerConnectApp', '0002_forumpost_image_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomicadvice',
            name='district',
            field=models.CharField(blank=True, help_text="Specific district or 'All'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agronomicadvice',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk (General)'), ('MEDIUM', 'Medium Risk (Guarded)'), ('HIGH', 'High Risk (Restricted)')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='agronomicadvice',
            name='season',
            field=models.CharField(choices=[('RAINY_A', 'Rainy Season A (Sept-Jan)'), ('RAINY_B', 'Rainy Season B (Feb-June)'), ('DRY_C', 'Dry Season C (July-Aug)'), ('ALL', 'All Seasons')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='agronomicadvice',
            name='soil_type',
            field=models.CharField(blank=True, help_text="e.g., 'Volcanic', 'Sandy Loam'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agronomicadvice',
            name='target_crop',
            field=models.CharField(blank=True, help_text="Specific crop (e.g., 'Maize (Hybrid 614)')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agronomicadvice',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='advice', to='EFarmerConnectApp.category'),
        ),
    ]
