# Generated by Django 5.2.7 on 2025-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EFarmerConnectApp', '0003_agronomicadvice_district_agronomicadvice_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='currency',
            field=models.CharField(default='RWF', max_length=10),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_images/'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='product_name',
            field=models.CharField(blank=True, help_text='Specific product name (e.g. Irish Potato)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='trend',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STABLE', 'Stable')], default='STABLE', max_length=10),
        ),
    ]
